### ISSUE TITLE
Users in admin area are not sorted 

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#311]
When you go to users in admi area, users in the table are not sorted by their last visited date as it was before. Now the order is random, you need to click on the arrows in last seen column header to sort it.

**Comment by anondev-sudo** [comment]
Solve: automatically sort the users by their last seen date

**Comment by AVMG20** [comment]
I see. It starts with sorting the last column (which are the buttons). Please note that when you click on the sorting, it also remembers the sorting in local storage. So next time you browse the user's page, it's sorted the way you like it.

**Comment by 1day2die** [comment]
this is fixed it seems

**Comment by anondev-sudo** [comment]
> 

It isn't fixed, still sorted wrong when you visit dashboard after pc reboot
